services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=aiddb'
      - 'POSTGRES_PASSWORD=admin123'
      - 'POSTGRES_USER=aidadmin'
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

